import type { Fish, Level, Project } from "../types";

export const projectsById: Record<string, Project> = {
    undergraduate: {
        id: "undergraduate",
        name: "The University of Auckland",
        title: "The University of Auckland",
        description:
            "Graduated with First Class Honours in a Bachelor of Software Engineering (Honours) from the University of Auckland in 2026," +
            " with a cumulative GPA of 8.5/9.0 (A+). Received the First in Course award for SOFTENG 281 and a Summer Research Scholarship.",
        stack: ["Software Engineering", "First Class Honours"],
        spotlightLabel: "Undergraduate",
    },
    "jane-street": {
        id: "jane-street",
        name: "Jane Street",
        title: "Jane Street Capital",
        description:
            "Trading Desk Operations Engineer (TDOE) intern at Jane Street Hong Kong from December 2025 to February 2026." +
            " Worked across both development and trading in a fast-paced environment, building tools to improve the efficiency" +
            " of trading desks. Learnt functional programming, market-making skills, and trading workflows.",
        stack: ["Quantitative Trading", "Market Making", "OCaml"],
        spotlightLabel: "Internship",
    },
    "neural-network": {
        id: "neural-network",
        name: "Neural Network",
        title: "Neural Network",
        description:
            "Built a lightweight neural network trained to detect different English accents from audio recordings." +
            " Trained using a custom dataset of five predominant English-speaking accents." +
            " Explored different training strategies and hyperparameters to evaluate the model's performance" +
            " and understand the impact of dataset composition on classification accuracy.",
        stack: ["Python", "NumPy", "Flask"],
        link: "https://github.com/adxmb/neural-network",
        spotlightLabel: "Project Spotlight",
    },
    "llm-test-oracles": {
        id: "llm-test-oracles",
        name: "LLM Research",
        title: "Understanding LLM-Driven Test Oracle Generation",
        description:
            "Researching Large Language Models' (LLMs) capabilities for test oracle generation with real-world bugs" +
            " and various prompting strategies at the University of Auckland. Developed a Python tool to automatically" +
            " evaluate the quality of test assertions generated by OpenAI and StarCoder LLMs against 36 bugs and 4" +
            " strategies over more than 2,000 tests. Published in AIware Conference, November 2025.",
        stack: ["Academic Research", "Java", "LLMs"],
        link: "https://ieeexplore.ieee.org/document/11334275",
        linkLabel: "View Paper",
        spotlightLabel: "Research Project",
    },
    "portfolio-website": {
        id: "portfolio-website",
        name: "Portfolio Website",
        title: "Portfolio Website",
        description:
            "A themed dive into the depths of my interests, projects, and experience." +
            " Designed to give an overview of my interests in software and life.",
        stack: ["React", "TypeScript", "Motion"],
        link: "https://github.com/adxmb/website",
        spotlightLabel: "Project Spotlight",
    },
    plantr: {
        id: "plantr",
        name: "AI Plant Matcher",
        title: "AI Plant Matcher",
        description:
            "A proof-of-concept web application created for the DEVs Hackathon with the theme Hack for Humanity." +
            " Plantr uses AI to make plant discovery engaging by allowing users to match with recommended plants based on their" +
            " profile via Tinder-esque swiping. 1st Place in UoA DEVS Hackathon 2024.",
        stack: ["React", "Node.js", "OpenAI"],
        link: "https://github.com/LocalhostLtd/DEV-Hackathon-2024",
        spotlightLabel: "Hackathon Project",
    },
    "deep-current": {
        id: "deep-current",
        name: "Deep Current",
        title: "Systems Thinking",
        description:
            "A research-driven concept for managing complex content flows without sacrificing clarity.",
        stack: ["System Design", "Strategy", "Content Ops"],
        spotlightLabel: "Project spotlight",
    },
    "blackwater-ui": {
        id: "blackwater-ui",
        name: "Blackwater UI",
        title: "Night Mode Interface",
        description:
            "An interface pattern study focused on accessible contrast, subtle motion, and low-noise clarity.",
        stack: ["UI Systems", "Accessibility", "Visual Design"],
        link: "https://github.com",
        spotlightLabel: "Project spotlight",
    },
};

export function buildProjectIdsByLevel(
    fishByLevel: Record<Level["id"], Fish[]>,
): Record<Level["id"], string[]> {
    const result = {} as Record<Level["id"], string[]>;

    for (const levelId of Object.keys(fishByLevel) as Level["id"][]) {
        result[levelId] = fishByLevel[levelId].map((fish) => fish.projectId);
    }

    return result;
}

export function getUniqueProjects(projectIds: string[]): Project[] {
    const seen = new Set<string>();
    const result: Project[] = [];

    for (const id of projectIds) {
        if (seen.has(id)) continue;
        const project = projectsById[id];
        if (!project) continue;
        seen.add(id);
        result.push(project);
    }

    return result;
}

export function getUniqueProjectsForFish(fishProjectIds: string[]): Project[] {
    const seen = new Set<string>();
    const result: Project[] = [];

    for (const id of fishProjectIds) {
        if (seen.has(id)) continue;
        const project = projectsById[id];
        if (!project) continue;
        seen.add(id);
        result.push(project);
    }

    return result;
}
