import type { Fish, Level, Project } from "../types";

export const projectsById: Record<string, Project> = {
    undergraduate: {
        id: "undergraduate",
        name: "The University of Auckland",
        title: "The University of Auckland",
        description:
            "Graduated with First Class Honours in a Bachelor of Software Engineering (Honours) from the University of Auckland in 2026," +
            " with a cumulative GPA of 8.5/9.0 (A+).\nReceived the First in Course award for SOFTENG 281 and a Summer Research Scholarship.\n",
        stack: ["Software Engineering", "First Class Honours"],
        spotlightLabel: "Undergraduate",
    },
    "jane-street": {
        id: "jane-street",
        name: "Jane Street",
        title: "Jane Street Capital",
        description:
            "Trading Desk Operations Engineer (TDOE) intern at Jane Street Hong Kong from December 2025 to February 2026." +
            " Worked across both development and trading in a fast-paced environment, building tools to improve the efficiency" +
            " of trading desks. Learnt functional programming, market-making skills, and trading workflows.\n",
        stack: ["Quantitative Trading", "Market Making", "OCaml"],
        spotlightLabel: "Internship",
    },
    "neural-network": {
        id: "neural-network",
        name: "Neural Network",
        title: "Neural Network",
        description:
            "Built a lightweight neural network trained to detect different English accents from audio recordings." +
            " Trained using a custom dataset of five predominant English-speaking accents.\n" +
            "Explored different training strategies and hyperparameters to evaluate the model's performance" +
            " and understand the impact of dataset composition on classification accuracy.\n",
        stack: ["Python", "NumPy", "Flask"],
        link: "https://github.com/adxmb/neural-network",
        spotlightLabel: "Project Spotlight",
    },
    "llm-test-oracles": {
        id: "llm-test-oracles",
        name: "LLM Research",
        title: "Understanding LLM-Driven Test Oracle Generation",
        description:
            "Researching Large Language Models' (LLMs) capabilities for test oracle generation with real-world bugs" +
            " and various prompting strategies at the University of Auckland.\nDeveloped a Python tool to automatically" +
            " evaluate the quality of test assertions generated by OpenAI and StarCoder LLMs against 36 bugs and 4" +
            " strategies over more than 2,000 tests. Published in AIware Conference, November 2025.\n",
        stack: ["Academic Research", "Java", "LLMs"],
        link: "https://ieeexplore.ieee.org/document/11334275",
        linkLabel: "View Paper",
        spotlightLabel: "Research Project",
    },
    "portfolio-website": {
        id: "portfolio-website",
        name: "Portfolio Website",
        title: "Portfolio Website",
        description:
            "A themed dive into the depths of my interests, projects, and experience." +
            " Designed to give an overview of my interests in software and life.\n",
        stack: ["React", "TypeScript", "Motion"],
        link: "https://github.com/adxmb/website",
        spotlightLabel: "Project Spotlight",
    },
    plantr: {
        id: "plantr",
        name: "AI Plant Matcher",
        title: "AI Plant Matcher",
        description:
            "A proof-of-concept web application created for the DEVs Hackathon with the theme Hack for Humanity." +
            " Plantr uses AI to make plant discovery engaging by allowing users to match with recommended plants based on their" +
            " profile via Tinder-esque swiping. 1st Place in UoA DEVS Hackathon 2024.\n",
        stack: ["React", "Node.js", "OpenAI"],
        link: "https://github.com/LocalhostLtd/DEV-Hackathon-2024",
        spotlightLabel: "Hackathon Project",
    },
    "current-activities": {
        id: "current-activities",
        name: "Current Activities",
        title: "What I'm Up To",
        description:
            "Practicing for piano diploma where I will be performing the following repertoire: <i>Liszt - Liebesträume no.3</i>, <i>Debussy - La plus que lente</i>," +
            " <i>Wilkinson - Oiseaux d’eau</i>, <i>Chopin - Ballade no.1</i>, and <i>Rachmaninov/Kreisler - Liebesleid</i>.\n" +
            "I've been attempting to perfect making <i>Choux au Craquelin</i> and a variety of different cakes and desserts " +
            "experimenting with different ratios, flavours, and types of fillings.\n" +
            "Recently I've been travelling around the world, picked up volleyball and basketball, and have been dabling other creative hobbies like sketching, writing, and photography too.\n",
        stack: ["Side Questing", "Updates"],
        spotlightLabel: "Side Quests",
    },
    movies: {
        id: "movies",
        name: "What I'm Watching",
        title: "Movie and TV Recommendations",
        description:
            "<b>12 Angry Men (1957)</b>, the biggest comeback in cinema history, just a compelling watch.\n" +
            "<b>Castle in the Sky (1986)</b>, a whimsical adventure exploring secrets hidden amongst the clouds.\n" +
            "<b>Do the Right Thing (1989)</b>, its the hottest day of the year and racial tensions are rising in Brooklyn.\n" +
            "<b>Sound of Metal (2019)</b>, heavy metal drummer grapples with hearing loss.\n" +
            "<b>Moonrise Kingdom (2012)</b>, two kids run away in the wilderness as various authorities try hunt them down.\n" +
            "<b>The Princess Bride (1987)</b>, a classic, easy watch for a more chill movie night.\n",
        stack: ["Certified Bangers", "Movies and TV"],
        spotlightLabel: "Movies and TV shows",
    },
};

export function buildProjectIdsByLevel(
    fishByLevel: Record<Level["id"], Fish[]>,
): Record<Level["id"], string[]> {
    const result = {} as Record<Level["id"], string[]>;

    for (const levelId of Object.keys(fishByLevel) as Level["id"][]) {
        result[levelId] = fishByLevel[levelId].map((fish) => fish.projectId);
    }

    return result;
}

export function getUniqueProjects(projectIds: string[]): Project[] {
    const seen = new Set<string>();
    const result: Project[] = [];

    for (const id of projectIds) {
        if (seen.has(id)) continue;
        const project = projectsById[id];
        if (!project) continue;
        seen.add(id);
        result.push(project);
    }

    return result;
}

export function getUniqueProjectsForFish(fishProjectIds: string[]): Project[] {
    const seen = new Set<string>();
    const result: Project[] = [];

    for (const id of fishProjectIds) {
        if (seen.has(id)) continue;
        const project = projectsById[id];
        if (!project) continue;
        seen.add(id);
        result.push(project);
    }

    return result;
}
